version: '3'

services:
  # MySQL Service
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aaloomysqlRootPassword
      MYSQL_DATABASE: aalooWordpressDatabase
      MYSQL_USER: aalooWordpressUser
      MYSQL_PASSWORD: aalooWordpressPassword
    networks:
      - wordpress_network

  # WordPress Service
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: aalooWordpressUser
      WORDPRESS_DB_PASSWORD: aalooWordpressPassword
      WORDPRESS_DB_NAME: aalooWordpressDatabase
    networks:
      - wordpress_network

  # phpMyAdmin Service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: somewordpress
    networks:
      - wordpress_network

# Volumes
volumes:
  db_data:
  wordpress_data:

# Networks
networks:
  wordpress_network:
    driver: bridge
